{"uuid": "c63bb46f-606c-42ea-9c0e-cdd5358b7313", "children": ["11473a58-81a1-415d-aac7-4421d56b5806"], "befores": [{"name": "init_fixture", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: unknown error: cannot determine loading status\nfrom disconnected: received Inspector.detached event\n  (Session info: chrome=102.0.5005.63)\nStacktrace:\nBacktrace:\n\tOrdinal0 [0x00B8B8F3+2406643]\n\tOrdinal0 [0x00B1AF31+1945393]\n\tOrdinal0 [0x00A0C748+837448]\n\tOrdinal0 [0x009FE6BE+779966]\n\tOrdinal0 [0x009FE2AF+778927]\n\tOrdinal0 [0x009FD8A6+776358]\n\tOrdinal0 [0x009FC7C5+772037]\n\tOrdinal0 [0x009FCDC8+773576]\n\tOrdinal0 [0x00A08BE0+822240]\n\tOrdinal0 [0x009FE0BD+778429]\n\tOrdinal0 [0x009FEC9A+781466]\n\tOrdinal0 [0x009FE2CA+778954]\n\tOrdinal0 [0x009FD8A6+776358]\n\tOrdinal0 [0x009FC7C5+772037]\n\tOrdinal0 [0x009FCC9D+773277]\n\tOrdinal0 [0x00A0DF4A+843594]\n\tOrdinal0 [0x00A64D3D+1199421]\n\tOrdinal0 [0x00A5427C+1131132]\n\tOrdinal0 [0x00A64682+1197698]\n\tOrdinal0 [0x00A54096+1130646]\n\tOrdinal0 [0x00A2E636+976438]\n\tOrdinal0 [0x00A2F546+980294]\n\tGetHandleVerifier [0x00DF9612+2498066]\n\tGetHandleVerifier [0x00DEC920+2445600]\n\tGetHandleVerifier [0x00C24F2A+579370]\n\tGetHandleVerifier [0x00C23D36+574774]\n\tOrdinal0 [0x00B21C0B+1973259]\n\tOrdinal0 [0x00B26688+1992328]\n\tOrdinal0 [0x00B26775+1992565]\n\tOrdinal0 [0x00B2F8D1+2029777]\n\tBaseThreadInitThunk [0x7719FA29+25]\n\tRtlGetAppContainerNamedObjectPath [0x77827A9E+286]\n\tRtlGetAppContainerNamedObjectPath [0x77827A6E+238]\n\n", "trace": "  File \"C:\\Users\\15572\\Desktop\\test\\.virtualenv\\nm_web-eiUOuFSS\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\15572\\Desktop\\test\\.virtualenv\\nm_web-eiUOuFSS\\lib\\site-packages\\_pytest\\fixtures.py\", line 1111, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\15572\\Desktop\\test\\.virtualenv\\nm_web-eiUOuFSS\\lib\\site-packages\\_pytest\\fixtures.py\", line 883, in call_fixture_func\n    fixture_result = next(generator)\n  File \"C:\\Users\\15572\\Desktop\\test\\nm_web\\project\\test_case\\conftest.py\", line 14, in init_fixture\n    driver.get(\"https://www.azazie.com\")\n  File \"C:\\Users\\15572\\Desktop\\test\\.virtualenv\\nm_web-eiUOuFSS\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 442, in get\n    self.execute(Command.GET, {'url': url})\n  File \"C:\\Users\\15572\\Desktop\\test\\.virtualenv\\nm_web-eiUOuFSS\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 430, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\15572\\Desktop\\test\\.virtualenv\\nm_web-eiUOuFSS\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 247, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1659192616793, "stop": 1659192619579}], "start": 1659192616793, "stop": 1659192619637}