{"uuid": "48e71e09-bb3e-4d44-bdf5-b385ef5d4343", "children": ["3f86e16a-87b2-469a-89df-b4ad11b7d7be"], "befores": [{"name": "back_login_page", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed\nfrom unknown error: web view not found\n  (Session info: chrome=102.0.5005.63)\nStacktrace:\nBacktrace:\n\tOrdinal0 [0x00B8B8F3+2406643]\n\tOrdinal0 [0x00B1AF31+1945393]\n\tOrdinal0 [0x00A0C748+837448]\n\tOrdinal0 [0x009F42B0+737968]\n\tOrdinal0 [0x00A56C09+1141769]\n\tOrdinal0 [0x00A63E22+1195554]\n\tOrdinal0 [0x00A54096+1130646]\n\tOrdinal0 [0x00A2E636+976438]\n\tOrdinal0 [0x00A2F546+980294]\n\tGetHandleVerifier [0x00DF9612+2498066]\n\tGetHandleVerifier [0x00DEC920+2445600]\n\tGetHandleVerifier [0x00C24F2A+579370]\n\tGetHandleVerifier [0x00C23D36+574774]\n\tOrdinal0 [0x00B21C0B+1973259]\n\tOrdinal0 [0x00B26688+1992328]\n\tOrdinal0 [0x00B26775+1992565]\n\tOrdinal0 [0x00B2F8D1+2029777]\n\tBaseThreadInitThunk [0x7719FA29+25]\n\tRtlGetAppContainerNamedObjectPath [0x77827A9E+286]\n\tRtlGetAppContainerNamedObjectPath [0x77827A6E+238]\n\n", "trace": "  File \"C:\\Users\\15572\\Desktop\\test\\.virtualenv\\nm_web-eiUOuFSS\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\15572\\Desktop\\test\\.virtualenv\\nm_web-eiUOuFSS\\lib\\site-packages\\_pytest\\fixtures.py\", line 1111, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\15572\\Desktop\\test\\.virtualenv\\nm_web-eiUOuFSS\\lib\\site-packages\\_pytest\\fixtures.py\", line 883, in call_fixture_func\n    fixture_result = next(generator)\n  File \"C:\\Users\\15572\\Desktop\\test\\nm_web\\project\\test_case\\conftest.py\", line 23, in back_login_page\n    init_fixture.get('https://www.azazie.com/user/login')\n  File \"C:\\Users\\15572\\Desktop\\test\\.virtualenv\\nm_web-eiUOuFSS\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 442, in get\n    self.execute(Command.GET, {'url': url})\n  File \"C:\\Users\\15572\\Desktop\\test\\.virtualenv\\nm_web-eiUOuFSS\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 430, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\15572\\Desktop\\test\\.virtualenv\\nm_web-eiUOuFSS\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 247, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1659192570827, "stop": 1659192570829}], "start": 1659192570827, "stop": 1659192570874}